export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const GET_PRODUCTS = "GET_PRODUCTS";

export const GET_CART_PRODUCTS = "GET_CART_PRODUCTS"
export const REMOVE_FROM_CART_PRODUCTS = "REMOVE_FROM_CART_PRODUCTS"
export const INCREMENT_QTY_CART_PRODUCTS = "INCREMENT_QTY_CART_PRODUCTS"
export const DECREMENT_QTY_CART_PRODUCTS = "DECREMENT_QTY_CART_PRODUCTS"
